name: ML Workflow CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas numpy matplotlib seaborn dagshub

      - name: Run MLflow Project
        run: mlflow run MLProject --env-manager=local

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns/
          retention-days: 7